// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto-collection/proto/dragon.proto

package dragonService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DragonService_SetValue_FullMethodName     = "/dragon.DragonService/SetValue"
	DragonService_GetValue_FullMethodName     = "/dragon.DragonService/GetValue"
	DragonService_LoadTestCall_FullMethodName = "/dragon.DragonService/LoadTestCall"
)

// DragonServiceClient is the client API for DragonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DragonServiceClient interface {
	SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*SetValueResponse, error)
	GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error)
	LoadTestCall(ctx context.Context, in *LoadTestRequest, opts ...grpc.CallOption) (*LoadTestResponse, error)
}

type dragonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDragonServiceClient(cc grpc.ClientConnInterface) DragonServiceClient {
	return &dragonServiceClient{cc}
}

func (c *dragonServiceClient) SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*SetValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetValueResponse)
	err := c.cc.Invoke(ctx, DragonService_SetValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dragonServiceClient) GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValueResponse)
	err := c.cc.Invoke(ctx, DragonService_GetValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dragonServiceClient) LoadTestCall(ctx context.Context, in *LoadTestRequest, opts ...grpc.CallOption) (*LoadTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadTestResponse)
	err := c.cc.Invoke(ctx, DragonService_LoadTestCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DragonServiceServer is the server API for DragonService service.
// All implementations must embed UnimplementedDragonServiceServer
// for forward compatibility.
type DragonServiceServer interface {
	SetValue(context.Context, *SetValueRequest) (*SetValueResponse, error)
	GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error)
	LoadTestCall(context.Context, *LoadTestRequest) (*LoadTestResponse, error)
	mustEmbedUnimplementedDragonServiceServer()
}

// UnimplementedDragonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDragonServiceServer struct{}

func (UnimplementedDragonServiceServer) SetValue(context.Context, *SetValueRequest) (*SetValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValue not implemented")
}
func (UnimplementedDragonServiceServer) GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedDragonServiceServer) LoadTestCall(context.Context, *LoadTestRequest) (*LoadTestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadTestCall not implemented")
}
func (UnimplementedDragonServiceServer) mustEmbedUnimplementedDragonServiceServer() {}
func (UnimplementedDragonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDragonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DragonServiceServer will
// result in compilation errors.
type UnsafeDragonServiceServer interface {
	mustEmbedUnimplementedDragonServiceServer()
}

func RegisterDragonServiceServer(s grpc.ServiceRegistrar, srv DragonServiceServer) {
	// If the following call pancis, it indicates UnimplementedDragonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DragonService_ServiceDesc, srv)
}

func _DragonService_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DragonServiceServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DragonService_SetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DragonServiceServer).SetValue(ctx, req.(*SetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DragonService_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DragonServiceServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DragonService_GetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DragonServiceServer).GetValue(ctx, req.(*GetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DragonService_LoadTestCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DragonServiceServer).LoadTestCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DragonService_LoadTestCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DragonServiceServer).LoadTestCall(ctx, req.(*LoadTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DragonService_ServiceDesc is the grpc.ServiceDesc for DragonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DragonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dragon.DragonService",
	HandlerType: (*DragonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetValue",
			Handler:    _DragonService_SetValue_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _DragonService_GetValue_Handler,
		},
		{
			MethodName: "LoadTestCall",
			Handler:    _DragonService_LoadTestCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto-collection/proto/dragon.proto",
}
