apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: redis-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: grpc-server
        image: grpc-dragonfly-usage:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_ADDR
          value: "redisdb-service:6379"
        - name: SERVER_PORT_ADDR
          value: "50052"
        ports:
        - containerPort: 50052
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-service
  namespace: redis-space
spec:
  selector:
    app: grpc-server
  ports:
  - protocol: TCP
    port: 50052
    targetPort: 50052

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdb
  namespace: redis-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisdb
  template:
    metadata:
      labels:
        app: redisdb
    spec:
      containers:
      - name: redisdb
        image: redis:latest
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redisdb-service
  namespace: redis-space
spec:
  selector:
    app: redisdb
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
